#%RAML 0.8
title: hybris Service Archetype
baseUri: /
version: v1
mediaType:  application/json

schemas:
  - wishlists: !include wishlists.json
  - wishlist: !include wishlist.json
  - wishlistItem: !include wishlistItem.json
  - error: !include https://api.yaas.io/patterns/v1/schema-error-message.json

traits: 
  - !include https://api.yaas.io/patterns/v2/trait-oauth2.yaml

resourceTypes: 
  - !include https://api.yaas.io/patterns/v2/resource-type-element.yaml
  - !include https://api.yaas.io/patterns/v1/resource-type-collection.yaml

/{tenant}/wishlists:
  type: collection
  is: [oauth2]
  get:
    description: Gets all wishlists
    responses:
      200:
        body:
          application/json:
            example: !include wishlists-example.json
  post:
    description: Creates a new wishlist
    body:
      application/json:
        example: !include wishlist-example.json

  /{wishlistId}:
    type: element
    is: [oauth2]
    uriParameters:
      wishlistId:
        description: the id of the wishlist to work on
        example: 784hti8ey
        type: string
    get:
      description: Gets a wishlist
      responses:
        200:
          body:
            application/json:
              example: !include wishlist-example.json

    put:
      description: Updates a wishlist
      body:
        application/json:
          example: !include wishlist-example.json

    delete:
      description: Deletes a wishlist
